# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

## This is figaro configuration of development environment.
# For OmniAuth
# (local test2)
#OMNIAUTH_GITHUB_KEY: e630d444e52372bae36e
#OMNIAUTH_GITHUB_SECRET: 770df3228e6018ed14bc0c0f1061e0f9ecb7d37c

OMNIAUTH_GITHUB_KEY: d9ace621056b74fd7882
OMNIAUTH_GITHUB_SECRET: c51ae94cd901abcebeeb9140ffddc068fa25da54
OMNIAUTH_TWITTER_KEY: KyySEEUVeybRoV31R8tFrg
OMNIAUTH_TWITTER_SECRET: jcNrySLZOfMAQhix70Ivtc9zziItuoj6m4mI2JCn9gY
OMNIAUTH_FACEBOOK_KEY: 288664691272998
OMNIAUTH_FACEBOOK_SECRET: 8e5c104f092b178e5d3d199b917b440b

# For E-Mail
MAIL_PASSWORD: summary0813
